[workspace]
members = ["oauth-credentials-ios", "oauth1-request", "oauth1-request-derive"]

[patch.crates-io]
oauth-credentials-ios = { path = "oauth-credentials-ios" }
oauth1-request = { path = "oauth1-request" }
oauth1-request-derive = { path = "oauth1-request-derive" }
